# Configuração de Conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/folha
spring.datasource.username=folha
spring.datasource.password=folha
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do Flyway - Habilitado para criar e migrar tabelas automaticamente
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

# Configuração do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Silenciar TOTALMENTE logs e banners do Spring para inicialização instantânea
spring.main.banner-mode=off
logging.level.root=ERROR
logging.level.org.springframework=ERROR
logging.level.org.hibernate=ERROR
logging.level.org.flywaydb=ERROR
logging.level.com.zaxxer.hikari=ERROR

# Desabilitar o console interativo padrão do Spring Shell (JLine livre de TTY)
spring.shell.interactive.enabled=false

# Habilitar o nosso menu customizado em produção
app.cli.enabled=true

# Ativar Inicialização Tardia (Lazy) para acelerar o startup inicial do Spring para <1s
spring.main.lazy-initialization=true
